{% set version = "1.1.0" %}

package:
  name: dust
  version: {{ version }}

source:
  url: https://github.com/bootandy/dust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2429b4ac76ad8520b99e7167dbb70c8e0088b5fad2c79f799e22b7d137d5fc33

build:
  number: 0
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" cargo install --path . --root "$PREFIX"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"                                   # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}     # [unix]
    - {{ stdlib('c') }}       # [unix]
    - m2w64-binutils          # [win]
    - cargo-bundle-licenses

test:
  commands:
    - dust --version

about:
  home: https://github.com/bootandy/dust
  summary: du + rust = dust. Like du but more intuitive.
  description: |
    An alternative tool for du to show disk usage in a more intuitive way.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://crates.io/crates/du-dust

extra:
  recipe-maintainers:
    - Zeitsperre
