{% set version = "1.0.0" %}

package:
  name: dust
  version: {{ version }}

source:
  url: https://github.com/bootandy/dust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 34b72116ab6db9bdb97bc1e49dadf392a1619838204b44b0a4695539d54ffbe8

build:
  number: 0
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" cargo install --path . --root "$PREFIX"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"                                   # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [unix]
    - m2w64-binutils       # [win]
    - cargo-bundle-licenses
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.13") }}  # [osx and x86_64]

test:
  commands:
    - dust --version

about:
  home: https://github.com/bootandy/dust
  summary: du + rust = dust. Like du but more intuitive.
  description: |
    An alternative tool for du to show disk usage in a more intuitive way.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://crates.io/crates/du-dust

extra:
  recipe-maintainers:
    - Zeitsperre
