{% set version = "1.1.1" %}

package:
  name: dust
  version: {{ version }}

source:
  url: https://github.com/bootandy/dust/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 98cae3e4b32514e51fcc1ed07fdbe6929d4b80942925348cc6e57b308d9c4cb0

build:
  number: 0
  script:
    - RUSTFLAGS="-Clink-args=-Wl,-L$PREFIX/lib" cargo install --path . --root "$PREFIX"  # [unix]
    - cargo install --path . --root "%LIBRARY_PREFIX%"                                   # [win]
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}     # [unix]
    - {{ stdlib('c') }}       # [unix]
    - m2w64-binutils          # [win]
    - cargo-bundle-licenses

test:
  commands:
    - dust --version

about:
  home: https://github.com/bootandy/dust
  summary: du + rust = dust. Like du but more intuitive.
  description: |
    An alternative tool for du to show disk usage in a more intuitive way.
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  dev_url: https://crates.io/crates/du-dust

extra:
  recipe-maintainers:
    - Zeitsperre
